demo:	demo.o keyboard.o xterm_control.o
	gcc demo.o keyboard.o xterm_control.o -o demo
	
demo.o:	demo.c
	gcc -c demo.c
	
keyboard.o:	keyboard.c
	gcc -c keyboard.c
	
xterm_control.o:	xterm_control.c
	gcc -c xterm_control.c
	
