battleship:	battleship.o keyboard.o xterm_control.o
	gcc battleship.o keyboard.o xterm_control.o -o battleship
	
battleship.o:	battleship.c
	gcc -c battleship.c
	
keyboard.o:	keyboard.c
	gcc -c keyboard.c
	
xterm_control.o:	x
term_control.c
	gcc -c xterm_control.c
	
